version: '3.9'


services:

  pg_movies_admin_panel:
    container_name: 'pg_movies_admin_panel'
    image: 'postgres:${POSTGRES_VERSION}'
    restart: always
    env_file:
      - .env
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data

  redis_movies_admin_panel:
    container_name: 'redis_movies_admin_panel'
    image: 'redis:${REDIS_VERSION}'
    restart: always
    env_file:
      - .env

  central_admin_panel_service:
    container_name: 'central_admin_panel_service'
    build:
      dockerfile: Dockerfile
      context: admin_panel
    restart: always
    env_file:
      - .env

    depends_on:
      - redis_movies_admin_panel
      - pg_movies_admin_panel

    links:
      - redis_movies_admin_panel
      - pg_movies_admin_panel
