version: "3.9"


services:

  pg_movies_admin_panel:
    container_name: "pg_movies_admin_panel"
    image: "postgres:${POSTGRES_VERSION}"
    restart: always
    env_file:
      - .env
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis_movies_admin_panel:
    container_name: "redis_movies_admin_panel"
    image: "redis:${REDIS_VERSION}"
    restart: always
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"


#  admin_service_vault:
#    image: "vault:latest"
#    restart: always
#    env_file:
#      - .env
#    ports:
#      - "8200:8200"
