version: '3.9'


services:

  pg_movies_admin_panel:
    container_name: 'pg_movies_admin_panel'
    image: 'postgres:${POSTGRES_VERSION}'
    restart: always
    env_file:
      - .env
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}'

  redis_movies_admin_panel:
    container_name: 'redis_movies_admin_panel'
    image: 'redis:${REDIS_VERSION}'
    restart: always
    env_file:
      - .env
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'


  central_admin_panel_service:
    container_name: 'central_admin_panel_service'
    build:
      dockerfile: Dockerfile
      context: admin_panel
    restart: always
    env_file:
      - .env
    volumes:
      - ./admin_panel:/usr/src/app
    links:
      - pg_movies_admin_panel
      - redis_movies_admin_panel

    ports:
      - '${APPLICATION_PORT}:${APPLICATION_PORT}'