# Generated by Django 4.1.4 on 2023-01-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_added_certificate_field_into_film_work_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmwork',
            name='certificate',
        ),
        migrations.AddField(
            model_name='filmwork',
            name='file_path',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to='movies/', verbose_name='file path'),
        ),
    ]
