name: Checking code
on: [ push ]
jobs:
  linter:
    name: Flake8
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Download Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: 'x64'
          cache: "pip"
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache
      - name: Download dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==3.9.0
          pip install wemake-python-styleguide

      - name: Flake8
        run: flake8 .